#################################
# PICOM CLEAN CONFIG
#################################

backend = "glx";
vsync = true;

#################################
# SHADOW
#################################

shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;

#################################
# FADING
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

#################################
# TRANSPARENCY
#################################

active-opacity = 1.0;
inactive-opacity = 0.85;

opacity-rule = [
  "85:class_g = 'Alacritty'",
  "90:class_g = 'firefox'",
  "90:class_g = 'LibreWolf'",
  "90:class_g = 'Chromium'",
  "90:class_g = 'code'",
  "90:class_g = 'VSCodium'",
  "90:class_g = 'Thunar'",
  "90:class_g = 'rofi'"
];

#################################
# BLUR
#################################

blur-method = "dual_kawase";
blur-strength = 7;
blur-background = true;
blur-background-frame = true;

shadow = true;
shadow-radius = 10;
shadow-opacity = 0.4;

#################################
# GENERAL
#################################

detect-client-opacity = true;
use-damage = true;
